"""add goods receipt tables

Revision ID: bd241b02bbd3
Revises: f144815caf89
Create Date: 2026-08-13 17:25:38.425402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd241b02bbd3'
down_revision: Union[str, Sequence[str], None] = 'f144815caf89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_id'), 'goods_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_purchase_order_id'), 'goods_receipts', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_receipt_number'), 'goods_receipts', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_goods_receipts_received_at'), 'goods_receipts', ['received_at'], unique=False)
    op.create_index(op.f('ix_goods_receipts_received_by'), 'goods_receipts', ['received_by'], unique=False)
    op.create_index(op.f('ix_goods_receipts_status'), 'goods_receipts', ['status'], unique=False)
    op.create_index(op.f('ix_goods_receipts_warehouse_id'), 'goods_receipts', ['warehouse_id'], unique=False)
    op.create_table('goods_receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_items_goods_receipt_id'), 'goods_receipt_items', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_id'), 'goods_receipt_items', ['id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_product_id'), 'goods_receipt_items', ['product_id'], unique=False)
    op.drop_index(op.f('ix_inventory_alerts_created_at'), table_name='inventory_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inventory_alerts_created_at'), 'inventory_alerts', ['created_at'], unique=False)
    op.drop_index(op.f('ix_goods_receipt_items_product_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_goods_receipt_id'), table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipts_warehouse_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_status'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_received_by'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_received_at'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_receipt_number'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_purchase_order_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    # ### end Alembic commands ###
