"""Improve warehouse model

Revision ID: c4f489eb4415
Revises: 50a9095a5efb
Create Date: 2026-08-10 11:19:48.685605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4f489eb4415'
down_revision: Union[str, Sequence[str], None] = '50a9095a5efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('warehouses', 'current_utilization',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('warehouses', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('warehouses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('warehouses_code_key'), 'warehouses', type_='unique')
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_status'), 'warehouses', ['status'], unique=False)
    op.drop_constraint(op.f('warehouses_manager_id_fkey'), 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('warehouses_manager_id_fkey'), 'warehouses', 'users', ['manager_id'], ['id'])
    op.drop_index(op.f('ix_warehouses_status'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.create_unique_constraint(op.f('warehouses_code_key'), 'warehouses', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('warehouses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('warehouses', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('warehouses', 'current_utilization',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('warehouses', 'updated_at')
    # ### end Alembic commands ###
